name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 10 * * 1
      
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        go: [ '1.11', '1.12', '1.13' ]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        
    - name: Test
      run: |
        go test -race ./...
  
  codecov:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go
      
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          
      - name: Generate Coverage Report
        run: |
          go test ./... -coverprofile=coverage.txt -covermode=atomic
        
      - name: Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
